### ISSUE TITLE
"AbortController is not defined" exception in new 1.0.0 version 

### ISSUE THREAD

**Issue by waldbaer** [bartbutenaers/node-red-contrib-multipart-stream-decoder#15]
Hello,

I just upgraded the stream decoder from version 0.0.4 to version 1.0.0
Unfortunately I always get the following exception when starting the decoding:

```
Feb 26 14:47:04 Node-RED[16661]: (node:16661) UnhandledPromiseRejectionWarning: ReferenceError: AbortController is not defined
Feb 26 14:47:04 Node-RED[16661]:     at MultiPartDecoder._inputCallback (/home/pi/.node-red/node_modules/node-red-contrib-multipart-stream-decoder/multipart_decoder.js:576:47)
Feb 26 14:47:04 Node-RED[16661]:     at /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
Feb 26 14:47:04 Node-RED[16661]:     at Object.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
Feb 26 14:47:04 Node-RED[16661]:     at MultiPartDecoder.Node._emitInput (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
Feb 26 14:47:04 Node-RED[16661]:     at MultiPartDecoder.Node.emit (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
Feb 26 14:47:04 Node-RED[16661]:     at MultiPartDecoder.Node.receive (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:485:10)
Feb 26 14:47:04 Node-RED[16661]:     at Immediate.<anonymous> (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52)
Feb 26 14:47:04 Node-RED[16661]:     at processImmediate (internal/timers.js:464:21)
```

When install the 1.0.0 on a fresh system the stream decoding is working as expected.

My used configuration:
```
[
    {
        "id": "e11c638eba2bb5ef",
        "type": "multipart-decoder",
        "z": "a8f633d.42bd75",
        "g": "1b18e108.edd3cf",
        "name": "",
        "ret": "bin",
        "url": "http://url.to.ipcam/video.cgi",
        "tls": "",
        "authentication": "basic",
        "delay": 0,
        "maximum": 1000000,
        "blockSize": 1,
        "enableLog": "off",
        "x": 870,
        "y": 1500,
        "wires": [
            [
                "bcfdc528.e179f8"
            ],
            []
        ]
    }
]
```

After a downgrade back to 0.0.4 to exception is gone.

Thanks for looking into this issue!

Best regards
Sebastian

**Comment by bartbutenaers** [comment]
Hi @waldbaer,

The Axios library that I use in version 1.0.0 of this node, indeed uses the AbortController.  I [see](https://nodejs.org/api/globals.html#class-abortcontroller) now that the AbortController is supported in NodeJs starting from versions v15.0.0 and v14.17.0.  Since NodeJs version 15.4.0 the AbortController was not longer experimental.

Could it be that you have on that failing system an older NodeJs version?  You can see the NodeJs version in your Node-RED startup log.  If that is the problem, I will need to add this as a requirement on the readme page of this node.

For older NodeJs versions there is a [node-abort-controller](https://github.com/southpolesteve/node-abort-controller) polyfill that I could have used.  However NodeJs version 14.x will be [end of life](https://github.com/nodejs/release#release-schedule) already on 2023-04-30 (and Node-RED follows the same [schedule](https://nodered.org/docs/faq/node-versions)), I am not going to support these old versions with this node.

Bart

**Comment by waldbaer** [comment]
Hello @bartbutenaers 

Thank you so much for your fast analysis!

I was actually running nodejs v14.21.3 on the affected system.
After upgrading to the latest nodejs v18.14.2 the mulitpart stream decoder is working again as expected!

Thanks again!

**Comment by bartbutenaers** [comment]
Hi @waldbaer,
Glad to hear that it is solved now.
I have added this requirement on the readme page, to avoid that others struggle with the same issue.
