### ISSUE TITLE
Issue trying to stream M JPEG from security camera using RTSP Stream

### ISSUE THREAD

**Issue by idt1201** [bartbutenaers/node-red-contrib-multipart-stream-decoder#3]
Using the address "rtsp://camera_address:554/video.mjpg" causes an error and no streaming takes place. using "camera_address:554/video.mjpg" works but the stream fails after a few frames. The rtsp address works fine in VLC. Any chance you could make this work? Currently I use the address without "rtsp://" and send a resume every few seconds! The Camera is an Intellinet net work camera type 551052.

Thanks

**Comment by bartbutenaers** [comment]
Hi @idt1201,

My node decodes mjpeg streams, but not rtsp since that is a completely other protocol.  An RTSP node for Node-RED is on my TODO list, but I'm currently too busy with other contributions.  

Got some time ago from another Node-Red user following link:
 https://www.youtube.com/watch?v=ihZWrJmbGFY&t=248s

Haven't tried that yet myself, but he told it was working fine...

Kind regards,
Bart

**Comment by bartbutenaers** [comment]
Hello @idt1201,
For your information: I have described in this Node-RED [discussion ](https://discourse.nodered.org/t/how-to-display-cctv-camera-in-dashboard-rtsp/5860/13?u=bartbutenaers)how to decode RTSP streams in Node-RED...

**Comment by idt1201** [comment]
Thanks for that I will give it a go.
